config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  devise_for :users

  mount Resque::Server.new, at: "/resque"
  
  root 'welcome#index'

  resources :accounts do
    member do
      get :show_transactions_list
      get :create_transaction
    end
  end

  resources :transactions

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.has_role?(:admin)
      # Admins can manage all
      can :manage, :all
    elsif user.has_role?(:user)
      # Users can read all and manage what they own
      can :read, :all
    else
      # Guests can read all
      can :read, :all
    end 
  end

end

app/models/account.rb
class Account < ActiveRecord::Base

  belongs_to :user

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base

  belongs_to :user
  belongs_to :transaction_status

  has_one :account_from, as: :account_from_id, class_name: 'Account'
  has_one :account_to,  as: :account_to_id, class_name: 'Account'

end

app/models/transaction_status.rb
class TransactionStatus < ActiveRecord::Base

  has_many :transactions

end

app/models/user.rb
class User < ActiveRecord::Base

  has_one :account
  has_many :transactions

  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy, :show_transactions_list, :create_transaction]
  before_action :authenticate_user!

  # GET /accounts
  def index
    if current_user.has_role?(:admin)
      @accounts = Account.all
    else
      @accounts = Account.where(:user_id => current_user.id)
    end
  end

  # GET /accounts/1
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  def create
    @account = Account.new(account_params)
    
    if @account.save
      redirect_to @account, notice: 'Account was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /accounts/1
  def update
    if @account.update(account_params)
      redirect_to @account, notice: 'Account was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /accounts/1
  def destroy
    @account.destroy
    redirect_to accounts_url, notice: 'Account was successfully destroyed.'
  end


  def show_transactions_list
    redirect_to transactions_path(:account_id => @account.id)
  end

  def create_transaction
    redirect_to new_transaction_path(:account_id => @account.id)
  end    

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def account_params
      params.require(:account).permit(:user_id, :code, :balance)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/transaction_statuses_controller.rb
class TransactionStatusesController < ApplicationController
  before_action :set_transaction_status, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /transaction_statuses
  def index
    @transaction_statuses = TransactionStatus.all
  end

  # GET /transaction_statuses/1
  def show
  end

  # GET /transaction_statuses/new
  def new
    @transaction_status = TransactionStatus.new
  end

  # GET /transaction_statuses/1/edit
  def edit
  end

  # POST /transaction_statuses
  def create
    @transaction_status = TransactionStatus.new(transaction_status_params)

    if @transaction_status.save
      redirect_to @transaction_status, notice: 'Transaction status was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /transaction_statuses/1
  def update
    if @transaction_status.update(transaction_status_params)
      redirect_to @transaction_status, notice: 'Transaction status was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /transaction_statuses/1
  def destroy
    @transaction_status.destroy
    redirect_to transaction_statuses_url, notice: 'Transaction status was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction_status
      @transaction_status = TransactionStatus.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def transaction_status_params
      params.require(:transaction_status).permit(:name)
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  @queue = :ruby_bank_transaction_process

  # GET /transactions
  def index
    if params[:account_id].blank?
      if current_user.has_role?(:admin)
        @transactions = Transaction.all
      else
        @transactions = nil
      end
    else
      @transactions = Transaction.where("account_from_id = ? OR account_to_id = ?", params[:account_id], params[:account_id])
    end
  end

  # GET /transactions/1
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
    @transaction.user_id = current_user.id
    @transaction.account_from_id = current_user.account.id
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  def create
    # check if amount is correct
    p transaction_params[:amount]
    if transaction_params[:amount].to_f.round(2) <= (current_user.account.balance - (current_user.account.blocked_amount.blank? ? 0 : current_user.account.blocked_amount ) )
      @transaction = Transaction.new(transaction_params)
      @transaction.user_id = current_user.id
      @transaction.account_from_id = current_user.account.id

      # block amount
      current_user.account.blocked_amount = 0 if current_user.account.blocked_amount.blank?
      current_user.account.blocked_amount += transaction_params[:amount].to_f.round(2)    

      # set status
      @transaction.status_id = TransactionStatus.where(name: 'Ordered').first.id;

      # save
      if current_user.account.save && @transaction.save
        # add background task for transaction
        Resque.enqueue(TransactionProcessingJob, @transaction.id)

        # redirect back to transactions
        redirect_to transactions_url(:account_id => current_user.account.id), notice: 'Transaction was successfully created.'
      else
        render :new
      end
    else
      redirect_to transactions_url(:account_id => current_user.account.id), notice: 'Sorry, you have not enough money to do the transfer.'
    end
  end

  # PATCH/PUT /transactions/1
  def update
    if @transaction.update(transaction_params)
      redirect_to @transaction, notice: 'Transaction was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /transactions/1
  def destroy
    @transaction.destroy
    redirect_to transactions_url, notice: 'Transaction was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def transaction_params
      params.require(:transaction).permit(:account_from_id, :account_to_id, :amount, :transaction_datetime, :status_id, :user_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/transaction_statuses_helper.rb
module TransactionStatusesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/accounts/_form.html.erb
<%= simple_form_for(@account) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id %>
    <%= f.input :code %>
    <%= f.input :balance %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<div class="page-header">
  <%= link_to accounts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @account, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing account</h1>
</div>

<%= render 'form' %>

app/views/accounts/index.html.erb
<div class="page-header">
  <h1>User Accounts</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>User</th>
        <th>Code</th>
        <th>Balance</th>
        <th>Blocked amount</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @accounts) do |account| %>
        <td><%= account.user.email %></td>
        <td><%= account.code %></td>
        <td><%= account.balance.blank? ? 0.00 : account.balance.round(2) %></td>
        <td><%= account.blocked_amount.blank? ? 0.00 : account.blocked_amount.round(2) %></td>
        <td><%= link_to 'Show transactions', show_transactions_list_account_path(account) %></td>
        <td><%= link_to 'Send money', create_transaction_account_path(account) %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/accounts/new.html.erb
<div class="page-header">
  <%= link_to accounts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New account</h1>
</div>

<%= render 'form' %>

app/views/accounts/show.html.erb
<div class="page-header">
  <%= link_to accounts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_account_path(@account), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show account</h1>
</div>

<dl class="dl-horizontal">
  <dt>User:</dt>
  <dd><%= @account.user_id %></dd>

  <dt>Code:</dt>
  <dd><%= @account.code %></dd>

  <dt>Balance:</dt>
  <dd><%= @account.balance %></dd>

</dl>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>

	<li>
    <a class="dropdown-toggle" id="dLabel" role="button" data-toggle="dropdown" data-target="#" href="/page.html">
      <%= fa_icon "2x cog",:text=>"Accounts" %>
      <b class="caret"></b>
    </a>

    <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
        <li><%= link_to "Accounts", accounts_path %></li>
    </ul>
	</li>

	<li>
    <a class="dropdown-toggle" id="dLabel" role="button" data-toggle="dropdown" data-target="#" href="/page.html">
      <%= fa_icon "2x cog",:text=>"Operations" %>
      <b class="caret"></b>
    </a>

    <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
	    <li><%= link_to "Transactions", show_transactions_list_account_path(current_user.account) %></li>
	    <li class="divider"></li>
  	  <li><%= link_to "Send money", create_transaction_account_path(current_user.account) %></li>
    </ul>
	</li>

	<li><%= link_to fa_icon("2x sign-out",:text=>"Logout " + current_user.email), destroy_user_session_path, :method=>"delete" %></li>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>The Ruby Bank</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "The Ruby Bank", "#", class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">

        <ul class="nav navbar-nav">
          <%= render 'layouts/navigation_links' %>
        </ul>


      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/transactions/_form.html.erb
<%= simple_form_for(@transaction, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :account_from_id, as: :select, :collection => [current_user.account.code], readonly: true, include_blank: false, :label => "Account from" %>
    <%= f.input :account_to_id, as: :select, :collection => Account.where.not(:user_id => current_user.id).collect {|r| [ r.user.email  + ' - ' + r.code, r.id ] }, include_blank: false, :label => "Account to"  %>
    <%= f.input :amount %>

    <%= f.input :status_id, :as => :hidden %>
    <%= f.input :user_id, :as => :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<div class="page-header">
  <%= link_to transactions_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @transaction, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing transaction</h1>
</div>

<%= render 'form' %>

app/views/transactions/index.html.erb
<script type="text/javascript">
function localize_time(element_id, t)
{
  var d = moment.utc(t, "YYYY-MM-DD HH:mm");
  document.getElementById(element_id).innerHTML = moment(d.toDate()).format("DD.MM.YYYY HH:mm");
}
</script>


<div class="page-header">
  <h1>Transactions</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Account from</th>
        <th>Account to</th>
        <th>Amount</th>
        <th>Date</th>
        <th>Status</th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @transactions) do |transaction| %>
        <td><%= Account.find(transaction.account_from_id).blank? ? 'Not defined' : Account.find(transaction.account_from_id).code %></td>
        <td><%= Account.find(transaction.account_to_id).blank? ? 'Not defined' : Account.find(transaction.account_to_id).code %></td>
        <td><%= transaction.amount %></td>
        <td><div id="<%= transaction.id.to_s %>"><script type="text/javascript">localize_time("<%= transaction.id.to_s %>", "<%= transaction.updated_at.strftime('%Y-%m-%d %H:%M') %>")</script></div></td>
        <td><%= TransactionStatus.find(transaction.status_id).blank? ? 'Not defined' : TransactionStatus.find(transaction.status_id).name %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/transactions/new.html.erb
<div class="page-header">
  <%= link_to transactions_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New transaction</h1>
</div>

<%= render 'form' %>

app/views/welcome/index.html.erb
<div class="page-header">
  <h1>Welcome</h1>
</div>

<div class="jumbotron">
  <p>Tiny Vault-Tech Bank</p>
  <% if !user_signed_in? %>
    <p><%= link_to "Sign in", new_user_session_path,:class=>"btn btn-lg btn-success" %></p>
  <% else %>
  	<p><%= link_to fa_icon("2x sign-out", :text=>"Logout"), destroy_user_session_path, :method=>"delete", :class=>"btn btn-danger" %></p>
  <% end %>
</div>